name: Model CI
on:
  push:
    branches:
    - 'master'
  pull_request:
    types: [opened]

jobs:
  build-model:
    name: Build, test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install rasa[spacy]
        python -m spacy download en_core_web_md
        python -m spacy link en_core_web_md en

    - name: Train model
      run: |
        rasa train

    - name: Run Through Test Stories
      run: |
        rasa test core --stories tests/conversation_tests.md --e2e --fail-on-prediction-errors
